### ISSUE TITLE
can't run app

### ISSUE THREAD

**Issue by tomoakley** [joykuotw/crazy-cards-app#1]
Hi Joy

I'm reviewing your code for TotallyMoney. I've tried to run both `yarn server` and `yarn start` but it errors with this message:
```
Error: Configuration property "mongoURI" is not defined                                                   
    at Config.get (/Users/tomoakley/Sites/crazy-cards-app/node_modules/config/lib/config.js:182:11)       
    at Object.<anonymous> (/Users/tomoakley/Sites/crazy-cards-app/config/db.js:3:19)                      
    at Module._compile (internal/modules/cjs/loader.js:1137:30)                                           
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)                             
    at Module.load (internal/modules/cjs/loader.js:985:32)                                                
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)                                      
    at Module.require (internal/modules/cjs/loader.js:1025:19)                                            
    at require (internal/modules/cjs/helpers.js:72:18)                                                    
    at Object.<anonymous> (/Users/tomoakley/Sites/crazy-cards-app/server.js:2:19)                         
    at Module._compile (internal/modules/cjs/loader.js:1137:30)                                           
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)                             
    at Module.load (internal/modules/cjs/loader.js:985:32)                                                
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)                                      
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)                   
    at internal/main/run_main_module.js:17:47         
```

I found `mongoURI` in `config/production.json`, but unsure how to get the property picked up by the config package. Can you advise?

**Comment by joykuotw** [comment]
Hi, thanks for the message.

To get the app running locally, make sure to run `yarn && yarn clientinstall` to install the dependencies first, and then `yarn dev`. This will run server and client concurrently.

As descried in the README, `yarn start` is to run the server but not listen to any changes. `yarn server` will run the server and listen to the changes.

**Comment by tomoakley** [comment]
Thanks Joy. I just tried `yarn dev`, but the server part of that command still has the same error. The client runs successfully.

**Comment by joykuotw** [comment]
I see. Can you please add a `default.json` under config folder so configuration can pick up?

Please add this property in the `default.json`:
```
{
  "mongoURI": "mongodb+srv://tester:vG5aMJ40t3WzFVED@joy.td8vp.mongodb.net/crazy-cards?retryWrites=true&w=majority"
}

```
This should solve the issue.

**Comment by tomoakley** [comment]
yeah that should work - also using `NODE_ENV=production yarn dev` works too. Thanks!

**Comment by joykuotw** [comment]
Thanks for the report. I have updated the README with usage manual.
